// Demo data for testing without backend
// Set DEMO_MODE = true in AuthContext.tsx to enable

export const DEMO_TOKEN_BALANCE = {
  available: 8,
  pending: 2,
  total: 10,
}

export const DEMO_USER_STATS = {
  totalClassesAttended: 24,
  tokensUsed: 24,
  currentStreak: 5,
}

export const DEMO_UPCOMING_BOOKINGS = [
  {
    id: 'booking-1',
    class_id: 'class-1',
    class_name: 'Dance Fitness',
    instructor_name: 'Maria Garcia',
    scheduled_at: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days from now
    duration_minutes: 60,
    location: 'Studio A',
    status: 'confirmed' as const,
    tokens_used: 1,
    booked_at: new Date().toISOString(),
  },
  {
    id: 'booking-2',
    class_id: 'class-2',
    class_name: 'Salsa Beginners',
    instructor_name: 'Carlos Rodriguez',
    scheduled_at: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(), // 4 days from now
    duration_minutes: 45,
    location: 'Studio B',
    status: 'confirmed' as const,
    tokens_used: 1,
    booked_at: new Date().toISOString(),
  },
]

export const DEMO_CLASSES = [
  {
    id: 'class-1',
    name: 'Dance Fitness',
    description: 'High-energy dance workout that combines Latin and international music with dance moves. Perfect for burning calories while having fun!',
    instructor_name: 'Maria Garcia',
    instructor_bio: 'Certified dance fitness instructor with 8 years of experience. Passionate about making fitness fun and accessible to everyone.',
    scheduled_at: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    duration_minutes: 60,
    location: 'Studio A',
    capacity: 25,
    booked_count: 18,
    tokens_required: 1,
    class_type: 'zumba',
    difficulty_level: 'Intermediate',
    requirements: ['Comfortable workout clothes', 'Good attitude!'],
    what_to_bring: ['Water bottle', 'Towel', 'Athletic shoes'],
  },
  {
    id: 'class-2',
    name: 'Salsa Beginners',
    description: 'Learn the basics of Salsa dancing in a fun and supportive environment. No partner or experience needed!',
    instructor_name: 'Carlos Rodriguez',
    instructor_bio: 'Professional Salsa dancer and choreographer. Has been teaching dance for over 10 years.',
    scheduled_at: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    duration_minutes: 45,
    location: 'Studio B',
    capacity: 20,
    booked_count: 12,
    tokens_required: 1,
    class_type: 'salsa',
    difficulty_level: 'Beginner',
    requirements: [],
    what_to_bring: ['Water bottle', 'Dance shoes or socks'],
  },
  {
    id: 'class-3',
    name: 'HIIT Dance Party',
    description: 'Combine high-intensity interval training with dance moves for the ultimate calorie-burning workout!',
    instructor_name: 'Jessica Williams',
    instructor_bio: 'Fitness enthusiast and certified personal trainer specializing in dance fitness.',
    scheduled_at: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    duration_minutes: 45,
    location: 'Studio A',
    capacity: 30,
    booked_count: 28,
    tokens_required: 1,
    class_type: 'hiit',
    difficulty_level: 'Advanced',
    requirements: ['Good cardiovascular fitness'],
    what_to_bring: ['Water bottle', 'Towel', 'Athletic shoes'],
  },
  {
    id: 'class-4',
    name: 'Yoga Flow',
    description: 'Gentle yoga class focusing on breath, flexibility, and mindfulness. Perfect for all levels.',
    instructor_name: 'Emily Chen',
    instructor_bio: '200-hour certified yoga instructor with a focus on mindful movement.',
    scheduled_at: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    duration_minutes: 60,
    location: 'Zen Room',
    capacity: 15,
    booked_count: 8,
    tokens_required: 1,
    class_type: 'yoga',
    difficulty_level: 'Beginner',
    requirements: [],
    what_to_bring: ['Yoga mat', 'Water bottle', 'Comfortable clothing'],
  },
  {
    id: 'class-5',
    name: 'Dance Fitness Fusion',
    description: 'A mix of different dance styles including hip-hop, latin, and contemporary. Great cardio workout!',
    instructor_name: 'Maria Garcia',
    instructor_bio: 'Certified dance fitness instructor with 8 years of experience.',
    scheduled_at: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    duration_minutes: 55,
    location: 'Studio A',
    capacity: 25,
    booked_count: 25,
    tokens_required: 1,
    class_type: 'dance',
    difficulty_level: 'Intermediate',
    requirements: [],
    what_to_bring: ['Water bottle', 'Towel', 'Athletic shoes'],
  },
  {
    id: 'class-6',
    name: 'Dance Fitness Gold',
    description: 'Lower intensity dance fitness class designed for active older adults or beginners. Same great music, easier moves!',
    instructor_name: 'Maria Garcia',
    instructor_bio: 'Certified dance fitness instructor with 8 years of experience.',
    scheduled_at: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    duration_minutes: 45,
    location: 'Studio B',
    capacity: 20,
    booked_count: 5,
    tokens_required: 1,
    class_type: 'zumba',
    difficulty_level: 'Beginner',
    requirements: [],
    what_to_bring: ['Water bottle', 'Comfortable shoes'],
  },
]

export const DEMO_PACKAGES = [
  {
    id: 'pkg-1',
    name: 'Starter Pack',
    description: 'Perfect for trying out our classes',
    token_count: 5,
    price: 4500, // $45.00 in cents
    currency: 'USD',
    validity_days: 30,
    is_popular: false,
    features: [],
  },
  {
    id: 'pkg-2',
    name: 'Fitness Enthusiast',
    description: 'Our most popular package for regular dancers',
    token_count: 10,
    price: 8000, // $80.00 in cents
    currency: 'USD',
    validity_days: 60,
    is_popular: true,
    features: ['Priority booking', '1 guest pass'],
  },
  {
    id: 'pkg-3',
    name: 'Unlimited Energy',
    description: 'Best value for dedicated fitness lovers',
    token_count: 20,
    price: 14000, // $140.00 in cents
    currency: 'USD',
    validity_days: 90,
    is_popular: false,
    features: ['Priority booking', '2 guest passes', 'Free merchandise'],
  },
]

export const DEMO_BOOKINGS = [
  ...DEMO_UPCOMING_BOOKINGS,
  {
    id: 'booking-3',
    class_id: 'class-past-1',
    class_name: 'Dance Fitness',
    instructor_name: 'Maria Garcia',
    scheduled_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), // 3 days ago
    duration_minutes: 60,
    location: 'Studio A',
    status: 'attended' as const,
    tokens_used: 1,
    booked_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'booking-4',
    class_id: 'class-past-2',
    class_name: 'HIIT Dance Party',
    instructor_name: 'Jessica Williams',
    scheduled_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days ago
    duration_minutes: 45,
    location: 'Studio A',
    status: 'attended' as const,
    tokens_used: 1,
    booked_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'booking-5',
    class_id: 'class-past-3',
    class_name: 'Yoga Flow',
    instructor_name: 'Emily Chen',
    scheduled_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), // 10 days ago
    duration_minutes: 60,
    location: 'Zen Room',
    status: 'cancelled' as const,
    tokens_used: 1,
    booked_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
